### ISSUE TITLE
API: CID vs Multihash

### ISSUE THREAD

**Issue by wanderer** [ipfs/js-ipfs-block-service#37]
it doesn't look like the block service need to know about CIDs only the multihash/key. It would be a bit nicer to work with if you do `bs.put(multihash, data)`

**Comment by wanderer** [comment]
oh ok https://github.com/ipfs/js-ipfs-block-service/blob/master/src/index.js#L27-L30

**Comment by daviddias** [comment]
exactly :) \o/ code comments :D
