### ISSUE TITLE
[for consideration] Move the notion of a 'online' block service to 'hasExchange'

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs-block-service#61]
ref:
- https://github.com/ipfs/js-ipfs-block-service/pull/58#discussion_r106649941
- https://github.com/ipfs/js-ipfs-block-service/pull/58#discussion_r106649882

Once we **start having more exchanges**, it will make it more obvious why this is interesting.

**Comment by daviddias** [comment]
//cc @dignifiedquire

**Comment by dignifiedquire** [comment]
I forgot to respond in the PR sorry. I generally like the idea, the online and offline names are pretty confusing

**Comment by pgte** [comment]
Simply renaming `.goOnline` to `.addExchange` is not accurate, as it would overwrite the previous bitswap. Should it be `setExchange`?

**Comment by daviddias** [comment]
@pgte agreed. What about the 'disable', rmExchange?

**Comment by pgte** [comment]
That, or `unsetExchange`. Perhaps consider also acting on `setExchange(null)`.

**Comment by dignifiedquire** [comment]
If the goal is to support multiple exchanges I wonder if it wouldn't be better to expose an api like this

```js
.exchanges.ls()
// => returns an array of existing exchanges
.exchanges.add(newExchange)
// => adds a new exchange to the list
.exchanges.rm(existingExchange)
// => removes the given exchange (might want to this by name or id or something like that 
.exchanges.clear()
// => removes all exchanges
.exchanges.has()
// => alias for .ls().length > 0
```

**Comment by daviddias** [comment]
I'm good either way. I agree that if we get more than one exchange it will be good to have such an API, but at the same time, we don't have any other nor plans for it.

Right now what is important to get fixed is the misleading method name.

**Comment by daviddias** [comment]
Done with #67
