### ISSUE TITLE
fails on phantom 

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs-block-service#7]
With the latest PR (ipld), the tests started failing on phantom (although they pass on travis, chrome and node.js)

```
11 04 2016 12:07:39.589:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket /#N7j5j_iOYICp_tS6AAAB with id 21504868
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  TypeError: 'undefined' is not an object (evaluating 'idb.deleteData/Users/david/code/protocol-labs/_ipfs/js/js-ipfs-blocks')
  at /Users/david/code/protocol-labs/_ipfs/js/js-ipfs-blocks/test/browser.js:46863
```

Do you see this error @dignifiedquire ? Could it be my env that I have something different?

**Comment by dignifiedquire** [comment]
Tests were passing fine locally with PhantomJS for me. Looks like you are using an outdated PhantomJS (1.x) were as dignified.js should bring a 2.x version. But that package does not upgrade if there is already a global PhantomJS binary installed. So get that updated and it should be fixed.

**Comment by daviddias** [comment]
that did it for me, thank you :) 

0.1.2 released!
